---
- name: Converge
  hosts: all
  become: yes

  vars:

  pre_tasks:
    - name: Install dependencies
      package:
        name: 'ca-certificates'
        state: present

  roles:
    - role: serverfriendsorg.speedtest_exporter
